# Generated by Django 4.2.19 on 2025-03-10 14:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("petrosa_app", "0002_project_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrueValueProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=300)),
                ("description", tinymce.models.HTMLField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(upload_to="truevalue_products/")),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name_plural": "TrueValue", "ordering": ("-created_at",),},
        ),
    ]
