# Generated by Django 4.2.19 on 2025-03-10 23:03

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("petrosa_app", "0003_truevalueproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("message", tinymce.models.HTMLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="petrosa_app.truevalueproduct",
                    ),
                ),
            ],
        ),
    ]
