# Generated by Django 3.2.3 on 2025-03-05 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrosa_app', '0003_auto_20250305_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
