# Generated by Django 5.1.7 on 2025-03-17 08:21

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrosa_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', tinymce.models.HTMLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petrosa_app.product')),
            ],
        ),
    ]
