# Generated by Django 5.1.7 on 2025-03-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrosa_app', '0002_productinterest'),
    ]

    operations = [
    ]
