# Generated by Django 5.1.7 on 2025-03-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrosa_energia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquote',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
