# Generated by Django 5.1.7 on 2025-03-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrosa_energia_app', '0002_quickquote_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quickquote',
            name='address',
        ),
    ]
