# Generated by Django 5.1.7 on 2025-03-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrosa_energia_app', '0003_remove_quickquote_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquote',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
